CREATE TABLE [User].[InternalCommand]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[OccuredOn] DATETIME2 NOT NULL,
	[Type] VARCHAR(255) NOT NULL,
	[Data] VARCHAR(MAX) NOT NULL,
	[ProcessedDate] DATETIME2 NULL,
	CONSTRAINT [PK_users_InternalCommands_Id] PRIMARY KEY ([Id] ASC)
)
