CREATE TABLE [User].[InternalCommand]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[OccuredOn] DATETIME2 NOT NULL,
	[Type] VARCHAR(255) NOT NULL,
	[Data] VARCHAR(MAX) NOT NULL,
	[ProcessedDate] DATETIME2 NULL,
	CONSTRAINT [PK_users_InternalCommands_Id] PRIMARY KEY ([Id] ASC),
	[ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
	[ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH(SYSTEM_VERSIONING = ON (HISTORY_TABLE = [User].[InternalCommandHistory]));

GO;

CREATE NONCLUSTERED INDEX [IX_User.InternalCommand_ProcessedDate]
ON [User].[InternalCommand] (Id)
WHERE ProcessedDate IS NULL;