CREATE TABLE [User].[UserRole]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [FK_User.UserRole_UserId] FOREIGN KEY REFERENCES [User].[User](Id),
	[RoleCode] SMALLINT,
	[ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
	[ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
	CONSTRAINT [PK_User.UserRole_UserId_RoleCode] PRIMARY KEY (UserId, RoleCode),
) WITH(SYSTEM_VERSIONING = ON (HISTORY_TABLE = [User].[UserRoleHistory]))

